language: rust
os:
    - linux
    - osx
rust: stable
cache: cargo

before_install:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "[skip travis] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi

script:
  - cargo test --features bindgen
