[package]
name = "hacl-star"
version = "0.0.3"
authors = ["quininer <quininer@live.com>"]
description = "HACL*, a formally verified cryptographic library for Rust (binding to hacl-c)."
keywords = [ "hacl-star", "cryptographic" ]
categories = [ "cryptography" ]
repository = "https://github.com/quininer/rust-hacl-star"
license = "MIT"

[workspace]

[features]
bindgen = [ "hacl-star-sys/bindgen" ]

[dependencies]
libc = { version = "0.2", default-features = false }
hacl-star-sys = { version = "0.0.3", path = "hacl-star-sys" }
